#ifndef AI_H
#define AI_H


enum AiType {
   AITYPE_MELEE,
   AITYPE_RANGED,
   AITYPE_HYDRA,
};

enum AiState {
	//Idle and substates
	AISTATE_IDLE,
	AISTATE_SLEEPING,
	AISTATE_WANDERING,

	//Attacking and substates
	AISTATE_ATTACKING,
	AISTATE_FLEEING,
   AISTATE_APPROACH_AND_WHACK,
   AISTATE_SHOOT_AND_APPROACH,
   AISTATE_SIT_AND_USE_ABILITY,

	//Total number of AI states
	AISTATE_TOTAL_STATES
};

#endif
