#ifndef ASCIISYMBOLS_H
#define ASCIISYMBOLS_H

#include <cstdint>

//Enums for ASCII tile ID (ASYM stands for Ascii SYMbol)
enum AsciiSymbol : uint8_t {
	ASYM_BLANK = 0,
	ASYM_SMILE_THIN, ASYM_SMILE_FILLED, ASYM_HEART, ASYM_SQUARE_DIAMOND,
	ASYM_DOT_LARGE = 7, ASYM_REVERSE_DOT_LARGE,
	ASYM_ARROW_UP = 24, ASYM_ARROW_DOWN, ASYM_ARROW_RIGHT, ASYM_ARROW_LEFT,
   ASYM_ARROW_LEFTRIGHT = 29, ASYM_FAT_ARROW_UP, ASYM_FAT_ARROW_DOWN,
	ASYM_SPACE = 32, ASYM_EXCLAMATION, ASYM_DOUBLE_QUOTES, ASYM_HASHTAG, ASYM_DOLLAR, ASYM_PERCENT,
	ASYM_AMPERSAND, ASYM_UFO, ASYM_LEFT_PARENTHESIS, ASYM_RIGHT_PARENTHESIS, ASYM_ASTERISK,
	ASYM_PLUS, ASYM_COMMA, ASYM_EM_DASH, ASYM_PERIOD, ASYM_FORWARD_SLASH,
	ASYM_ZERO, ASYM_ONE, ASYM_TWO, ASYM_THREE, ASYM_FOUR, ASYM_FIVE, ASYM_SIX,
	ASYM_SEVEN, ASYM_EIGHT, ASYM_NINE,
	ASYM_COLON, ASYM_SEMICOLON, ASYM_LESS_THAN, ASYM_EQUAL, ASYM_GREATER_THAN,
	ASYM_QUESTION_MARK,
	ASYM_AT = 64,
   ASYM_UPPER_A, ASYM_UPPER_B, ASYM_UPPER_C, ASYM_UPPER_D, ASYM_UPPER_E, ASYM_UPPER_F, ASYM_UPPER_G,
   ASYM_UPPER_H, ASYM_UPPER_I, ASYM_UPPER_J, ASYM_UPPER_K, ASYM_UPPER_L, ASYM_UPPER_M, ASYM_UPPER_N,
   ASYM_UPPER_O,
   ASYM_UPPER_P = 80, ASYM_UPPER_Q, ASYM_UPPER_R, ASYM_UPPER_S, ASYM_UPPER_T, ASYM_UPPER_U,
   ASYM_UPPER_V, ASYM_UPPER_W, ASYM_UPPER_X, ASYM_UPPER_Y, ASYM_UPPER_Z,
   ASYM_SQARE_BRACKET_LEFT, ASYM_BACKSLASH, ASYM_SQARE_BRACKET_RIGHT, ASYM_CARET, ASYM_UNDERSCORE,
   ASYM_SINGLE_QUOTE = 96,
   ASYM_LOWER_A, ASYM_LOWER_B, ASYM_LOWER_C, ASYM_LOWER_D, ASYM_LOWER_E, ASYM_LOWER_F, ASYM_LOWER_G,
   ASYM_LOWER_H, ASYM_LOWER_I, ASYM_LOWER_J, ASYM_LOWER_K, ASYM_LOWER_L, ASYM_LOWER_M, ASYM_LOWER_N,
   ASYM_LOWER_O,
   ASYM_LOWER_P = 112, ASYM_LOWER_Q, ASYM_LOWER_R, ASYM_LOWER_S, ASYM_LOWER_T, ASYM_LOWER_U,
   ASYM_LOWER_V, ASYM_LOWER_W, ASYM_LOWER_X, ASYM_LOWER_Y, ASYM_LOWER_Z,
   ASYM_CURLY_BRACKET_LEFT, ASYM_VERTICAL_DIVIDER, ASYM_CURLY_BRACKET_RIGHT, ASYM_TILDE, ASYM_PYRAMID,
	ASYM_DOTS = 176,
	ASYM_BLOCK = 219,
	ASYM_DOT = 249, ASYM_SMALL_DASH,
	ASYM_RETICLE = 255
};

#endif
